{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logging HW",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json",
     "legendFormat": "Logging HW"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_total{method=\"all\"}[1m])",
     "legendFormat": "all"
    },
    {
     "expr": "rate(request_total{method=\"post\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(request_total{method=\"get\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(request_total{method=\"delete\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(request_total{method=\"put\"}[1m])",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "authenticate_total{method=\"users_logged_in\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Authentication Attempts/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "changes(authenticate_total{method=\"successful_authentication\"}[1m])",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(authenticate_total{method=\"failed_authentication\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_usage{method=\"cpu\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "os_usage{method=\"memory\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizza_total{method=\"pizzas_sold\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(pizza_total{method=\"pizza_failure_creation_total\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_total_total{method=\"total_revenue\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "request_total{method=\"all_request_latency\"}",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "order_total{method=\"pizza_creation_latency\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  }
 ]
}